#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="namngu")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttblcustomer8(tblcustomer8 instance);
    partial void Updatetblcustomer8(tblcustomer8 instance);
    partial void Deletetblcustomer8(tblcustomer8 instance);
    partial void Inserttbldegree8(tbldegree8 instance);
    partial void Updatetbldegree8(tbldegree8 instance);
    partial void Deletetbldegree8(tbldegree8 instance);
    partial void Inserttbldistributor8(tbldistributor8 instance);
    partial void Updatetbldistributor8(tbldistributor8 instance);
    partial void Deletetbldistributor8(tbldistributor8 instance);
    partial void Inserttblexport8(tblexport8 instance);
    partial void Updatetblexport8(tblexport8 instance);
    partial void Deletetblexport8(tblexport8 instance);
    partial void Inserttblexportdetail8(tblexportdetail8 instance);
    partial void Updatetblexportdetail8(tblexportdetail8 instance);
    partial void Deletetblexportdetail8(tblexportdetail8 instance);
    partial void Inserttblimport8(tblimport8 instance);
    partial void Updatetblimport8(tblimport8 instance);
    partial void Deletetblimport8(tblimport8 instance);
    partial void Inserttblimportdetail8(tblimportdetail8 instance);
    partial void Updatetblimportdetail8(tblimportdetail8 instance);
    partial void Deletetblimportdetail8(tblimportdetail8 instance);
    partial void Inserttblproduct8(tblproduct8 instance);
    partial void Updatetblproduct8(tblproduct8 instance);
    partial void Deletetblproduct8(tblproduct8 instance);
    partial void Inserttblstaff8(tblstaff8 instance);
    partial void Updatetblstaff8(tblstaff8 instance);
    partial void Deletetblstaff8(tblstaff8 instance);
    partial void Inserttbltype8(tbltype8 instance);
    partial void Updatetbltype8(tbltype8 instance);
    partial void Deletetbltype8(tbltype8 instance);
    partial void Inserttbluser8(tbluser8 instance);
    partial void Updatetbluser8(tbluser8 instance);
    partial void Deletetbluser8(tbluser8 instance);
    #endregion
		
		public DBDataContext() : 
				base(global::DAL.Properties.Settings.Default.namnguConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblcustomer8> tblcustomer8s
		{
			get
			{
				return this.GetTable<tblcustomer8>();
			}
		}
		
		public System.Data.Linq.Table<tbldegree8> tbldegree8s
		{
			get
			{
				return this.GetTable<tbldegree8>();
			}
		}
		
		public System.Data.Linq.Table<tbldistributor8> tbldistributor8s
		{
			get
			{
				return this.GetTable<tbldistributor8>();
			}
		}
		
		public System.Data.Linq.Table<tblexport8> tblexport8s
		{
			get
			{
				return this.GetTable<tblexport8>();
			}
		}
		
		public System.Data.Linq.Table<tblexportdetail8> tblexportdetail8s
		{
			get
			{
				return this.GetTable<tblexportdetail8>();
			}
		}
		
		public System.Data.Linq.Table<tblimport8> tblimport8s
		{
			get
			{
				return this.GetTable<tblimport8>();
			}
		}
		
		public System.Data.Linq.Table<tblimportdetail8> tblimportdetail8s
		{
			get
			{
				return this.GetTable<tblimportdetail8>();
			}
		}
		
		public System.Data.Linq.Table<tblproduct8> tblproduct8s
		{
			get
			{
				return this.GetTable<tblproduct8>();
			}
		}
		
		public System.Data.Linq.Table<tblstaff8> tblstaff8s
		{
			get
			{
				return this.GetTable<tblstaff8>();
			}
		}
		
		public System.Data.Linq.Table<tbltype8> tbltype8s
		{
			get
			{
				return this.GetTable<tbltype8>();
			}
		}
		
		public System.Data.Linq.Table<tbluser8> tbluser8s
		{
			get
			{
				return this.GetTable<tbluser8>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblcustomer8")]
	public partial class tblcustomer8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _customer_id;
		
		private string _customer_name;
		
		private System.DateTime _customer_birth;
		
		private string _customer_gender;
		
		private string _customer_id_card;
		
		private string _customer_address;
		
		private string _customer_phone;
		
		private EntitySet<tblexport8> _tblexport8s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_idChanging(string value);
    partial void Oncustomer_idChanged();
    partial void Oncustomer_nameChanging(string value);
    partial void Oncustomer_nameChanged();
    partial void Oncustomer_birthChanging(System.DateTime value);
    partial void Oncustomer_birthChanged();
    partial void Oncustomer_genderChanging(string value);
    partial void Oncustomer_genderChanged();
    partial void Oncustomer_id_cardChanging(string value);
    partial void Oncustomer_id_cardChanged();
    partial void Oncustomer_addressChanging(string value);
    partial void Oncustomer_addressChanged();
    partial void Oncustomer_phoneChanging(string value);
    partial void Oncustomer_phoneChanged();
    #endregion
		
		public tblcustomer8()
		{
			this._tblexport8s = new EntitySet<tblexport8>(new Action<tblexport8>(this.attach_tblexport8s), new Action<tblexport8>(this.detach_tblexport8s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				if ((this._customer_name != value))
				{
					this.Oncustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._customer_name = value;
					this.SendPropertyChanged("customer_name");
					this.Oncustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_birth", DbType="Date NOT NULL")]
		public System.DateTime customer_birth
		{
			get
			{
				return this._customer_birth;
			}
			set
			{
				if ((this._customer_birth != value))
				{
					this.Oncustomer_birthChanging(value);
					this.SendPropertyChanging();
					this._customer_birth = value;
					this.SendPropertyChanged("customer_birth");
					this.Oncustomer_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_gender", DbType="NChar(10)")]
		public string customer_gender
		{
			get
			{
				return this._customer_gender;
			}
			set
			{
				if ((this._customer_gender != value))
				{
					this.Oncustomer_genderChanging(value);
					this.SendPropertyChanging();
					this._customer_gender = value;
					this.SendPropertyChanged("customer_gender");
					this.Oncustomer_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id_card", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string customer_id_card
		{
			get
			{
				return this._customer_id_card;
			}
			set
			{
				if ((this._customer_id_card != value))
				{
					this.Oncustomer_id_cardChanging(value);
					this.SendPropertyChanging();
					this._customer_id_card = value;
					this.SendPropertyChanged("customer_id_card");
					this.Oncustomer_id_cardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_address", DbType="NVarChar(MAX)")]
		public string customer_address
		{
			get
			{
				return this._customer_address;
			}
			set
			{
				if ((this._customer_address != value))
				{
					this.Oncustomer_addressChanging(value);
					this.SendPropertyChanging();
					this._customer_address = value;
					this.SendPropertyChanged("customer_address");
					this.Oncustomer_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_phone", DbType="VarChar(50)")]
		public string customer_phone
		{
			get
			{
				return this._customer_phone;
			}
			set
			{
				if ((this._customer_phone != value))
				{
					this.Oncustomer_phoneChanging(value);
					this.SendPropertyChanging();
					this._customer_phone = value;
					this.SendPropertyChanged("customer_phone");
					this.Oncustomer_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcustomer8_tblexport8", Storage="_tblexport8s", ThisKey="customer_id", OtherKey="export_customer_id")]
		public EntitySet<tblexport8> tblexport8s
		{
			get
			{
				return this._tblexport8s;
			}
			set
			{
				this._tblexport8s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblexport8s(tblexport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblcustomer8 = this;
		}
		
		private void detach_tblexport8s(tblexport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblcustomer8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbldegree8")]
	public partial class tbldegree8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _degree_id;
		
		private string _degree_name;
		
		private EntitySet<tblstaff8> _tblstaff8s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondegree_idChanging(string value);
    partial void Ondegree_idChanged();
    partial void Ondegree_nameChanging(string value);
    partial void Ondegree_nameChanged();
    #endregion
		
		public tbldegree8()
		{
			this._tblstaff8s = new EntitySet<tblstaff8>(new Action<tblstaff8>(this.attach_tblstaff8s), new Action<tblstaff8>(this.detach_tblstaff8s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string degree_id
		{
			get
			{
				return this._degree_id;
			}
			set
			{
				if ((this._degree_id != value))
				{
					this.Ondegree_idChanging(value);
					this.SendPropertyChanging();
					this._degree_id = value;
					this.SendPropertyChanged("degree_id");
					this.Ondegree_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree_name", DbType="NVarChar(50)")]
		public string degree_name
		{
			get
			{
				return this._degree_name;
			}
			set
			{
				if ((this._degree_name != value))
				{
					this.Ondegree_nameChanging(value);
					this.SendPropertyChanging();
					this._degree_name = value;
					this.SendPropertyChanged("degree_name");
					this.Ondegree_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbldegree8_tblstaff8", Storage="_tblstaff8s", ThisKey="degree_id", OtherKey="staff_degree_id")]
		public EntitySet<tblstaff8> tblstaff8s
		{
			get
			{
				return this._tblstaff8s;
			}
			set
			{
				this._tblstaff8s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblstaff8s(tblstaff8 entity)
		{
			this.SendPropertyChanging();
			entity.tbldegree8 = this;
		}
		
		private void detach_tblstaff8s(tblstaff8 entity)
		{
			this.SendPropertyChanging();
			entity.tbldegree8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbldistributor8")]
	public partial class tbldistributor8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _distributor_id;
		
		private string _distributor_name;
		
		private string _distributor_address;
		
		private string _distributor_phone;
		
		private string _distributor_email;
		
		private EntitySet<tblimport8> _tblimport8s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondistributor_idChanging(string value);
    partial void Ondistributor_idChanged();
    partial void Ondistributor_nameChanging(string value);
    partial void Ondistributor_nameChanged();
    partial void Ondistributor_addressChanging(string value);
    partial void Ondistributor_addressChanged();
    partial void Ondistributor_phoneChanging(string value);
    partial void Ondistributor_phoneChanged();
    partial void Ondistributor_emailChanging(string value);
    partial void Ondistributor_emailChanged();
    #endregion
		
		public tbldistributor8()
		{
			this._tblimport8s = new EntitySet<tblimport8>(new Action<tblimport8>(this.attach_tblimport8s), new Action<tblimport8>(this.detach_tblimport8s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string distributor_id
		{
			get
			{
				return this._distributor_id;
			}
			set
			{
				if ((this._distributor_id != value))
				{
					this.Ondistributor_idChanging(value);
					this.SendPropertyChanging();
					this._distributor_id = value;
					this.SendPropertyChanged("distributor_id");
					this.Ondistributor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_name", DbType="NVarChar(MAX)")]
		public string distributor_name
		{
			get
			{
				return this._distributor_name;
			}
			set
			{
				if ((this._distributor_name != value))
				{
					this.Ondistributor_nameChanging(value);
					this.SendPropertyChanging();
					this._distributor_name = value;
					this.SendPropertyChanged("distributor_name");
					this.Ondistributor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_address", DbType="NVarChar(MAX)")]
		public string distributor_address
		{
			get
			{
				return this._distributor_address;
			}
			set
			{
				if ((this._distributor_address != value))
				{
					this.Ondistributor_addressChanging(value);
					this.SendPropertyChanging();
					this._distributor_address = value;
					this.SendPropertyChanged("distributor_address");
					this.Ondistributor_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_phone", DbType="Char(20)")]
		public string distributor_phone
		{
			get
			{
				return this._distributor_phone;
			}
			set
			{
				if ((this._distributor_phone != value))
				{
					this.Ondistributor_phoneChanging(value);
					this.SendPropertyChanging();
					this._distributor_phone = value;
					this.SendPropertyChanged("distributor_phone");
					this.Ondistributor_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distributor_email", DbType="Char(50)")]
		public string distributor_email
		{
			get
			{
				return this._distributor_email;
			}
			set
			{
				if ((this._distributor_email != value))
				{
					this.Ondistributor_emailChanging(value);
					this.SendPropertyChanging();
					this._distributor_email = value;
					this.SendPropertyChanged("distributor_email");
					this.Ondistributor_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbldistributor8_tblimport8", Storage="_tblimport8s", ThisKey="distributor_id", OtherKey="import_distributor_id")]
		public EntitySet<tblimport8> tblimport8s
		{
			get
			{
				return this._tblimport8s;
			}
			set
			{
				this._tblimport8s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblimport8s(tblimport8 entity)
		{
			this.SendPropertyChanging();
			entity.tbldistributor8 = this;
		}
		
		private void detach_tblimport8s(tblimport8 entity)
		{
			this.SendPropertyChanging();
			entity.tbldistributor8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblexport8")]
	public partial class tblexport8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _export_id;
		
		private System.Nullable<System.DateTime> _export_date;
		
		private string _export_staff_id;
		
		private string _export_customer_id;
		
		private EntitySet<tblexportdetail8> _tblexportdetail8s;
		
		private EntityRef<tblcustomer8> _tblcustomer8;
		
		private EntityRef<tblstaff8> _tblstaff8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onexport_idChanging(string value);
    partial void Onexport_idChanged();
    partial void Onexport_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onexport_dateChanged();
    partial void Onexport_staff_idChanging(string value);
    partial void Onexport_staff_idChanged();
    partial void Onexport_customer_idChanging(string value);
    partial void Onexport_customer_idChanged();
    #endregion
		
		public tblexport8()
		{
			this._tblexportdetail8s = new EntitySet<tblexportdetail8>(new Action<tblexportdetail8>(this.attach_tblexportdetail8s), new Action<tblexportdetail8>(this.detach_tblexportdetail8s));
			this._tblcustomer8 = default(EntityRef<tblcustomer8>);
			this._tblstaff8 = default(EntityRef<tblstaff8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string export_id
		{
			get
			{
				return this._export_id;
			}
			set
			{
				if ((this._export_id != value))
				{
					this.Onexport_idChanging(value);
					this.SendPropertyChanging();
					this._export_id = value;
					this.SendPropertyChanged("export_id");
					this.Onexport_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_date", DbType="Date")]
		public System.Nullable<System.DateTime> export_date
		{
			get
			{
				return this._export_date;
			}
			set
			{
				if ((this._export_date != value))
				{
					this.Onexport_dateChanging(value);
					this.SendPropertyChanging();
					this._export_date = value;
					this.SendPropertyChanged("export_date");
					this.Onexport_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_staff_id", DbType="Char(50)")]
		public string export_staff_id
		{
			get
			{
				return this._export_staff_id;
			}
			set
			{
				if ((this._export_staff_id != value))
				{
					if (this._tblstaff8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onexport_staff_idChanging(value);
					this.SendPropertyChanging();
					this._export_staff_id = value;
					this.SendPropertyChanged("export_staff_id");
					this.Onexport_staff_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_customer_id", DbType="Char(50)")]
		public string export_customer_id
		{
			get
			{
				return this._export_customer_id;
			}
			set
			{
				if ((this._export_customer_id != value))
				{
					if (this._tblcustomer8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onexport_customer_idChanging(value);
					this.SendPropertyChanging();
					this._export_customer_id = value;
					this.SendPropertyChanged("export_customer_id");
					this.Onexport_customer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblexport8_tblexportdetail8", Storage="_tblexportdetail8s", ThisKey="export_id", OtherKey="export_detail_export_id")]
		public EntitySet<tblexportdetail8> tblexportdetail8s
		{
			get
			{
				return this._tblexportdetail8s;
			}
			set
			{
				this._tblexportdetail8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblcustomer8_tblexport8", Storage="_tblcustomer8", ThisKey="export_customer_id", OtherKey="customer_id", IsForeignKey=true)]
		public tblcustomer8 tblcustomer8
		{
			get
			{
				return this._tblcustomer8.Entity;
			}
			set
			{
				tblcustomer8 previousValue = this._tblcustomer8.Entity;
				if (((previousValue != value) 
							|| (this._tblcustomer8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblcustomer8.Entity = null;
						previousValue.tblexport8s.Remove(this);
					}
					this._tblcustomer8.Entity = value;
					if ((value != null))
					{
						value.tblexport8s.Add(this);
						this._export_customer_id = value.customer_id;
					}
					else
					{
						this._export_customer_id = default(string);
					}
					this.SendPropertyChanged("tblcustomer8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblstaff8_tblexport8", Storage="_tblstaff8", ThisKey="export_staff_id", OtherKey="staff_id", IsForeignKey=true)]
		public tblstaff8 tblstaff8
		{
			get
			{
				return this._tblstaff8.Entity;
			}
			set
			{
				tblstaff8 previousValue = this._tblstaff8.Entity;
				if (((previousValue != value) 
							|| (this._tblstaff8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblstaff8.Entity = null;
						previousValue.tblexport8s.Remove(this);
					}
					this._tblstaff8.Entity = value;
					if ((value != null))
					{
						value.tblexport8s.Add(this);
						this._export_staff_id = value.staff_id;
					}
					else
					{
						this._export_staff_id = default(string);
					}
					this.SendPropertyChanged("tblstaff8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblexportdetail8s(tblexportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblexport8 = this;
		}
		
		private void detach_tblexportdetail8s(tblexportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblexport8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblexportdetail8")]
	public partial class tblexportdetail8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _export_detail_export_id;
		
		private string _export_detail_product_id;
		
		private System.Nullable<int> _export_amount;
		
		private EntityRef<tblexport8> _tblexport8;
		
		private EntityRef<tblproduct8> _tblproduct8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onexport_detail_export_idChanging(string value);
    partial void Onexport_detail_export_idChanged();
    partial void Onexport_detail_product_idChanging(string value);
    partial void Onexport_detail_product_idChanged();
    partial void Onexport_amountChanging(System.Nullable<int> value);
    partial void Onexport_amountChanged();
    #endregion
		
		public tblexportdetail8()
		{
			this._tblexport8 = default(EntityRef<tblexport8>);
			this._tblproduct8 = default(EntityRef<tblproduct8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_detail_export_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string export_detail_export_id
		{
			get
			{
				return this._export_detail_export_id;
			}
			set
			{
				if ((this._export_detail_export_id != value))
				{
					if (this._tblexport8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onexport_detail_export_idChanging(value);
					this.SendPropertyChanging();
					this._export_detail_export_id = value;
					this.SendPropertyChanged("export_detail_export_id");
					this.Onexport_detail_export_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_detail_product_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string export_detail_product_id
		{
			get
			{
				return this._export_detail_product_id;
			}
			set
			{
				if ((this._export_detail_product_id != value))
				{
					if (this._tblproduct8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onexport_detail_product_idChanging(value);
					this.SendPropertyChanging();
					this._export_detail_product_id = value;
					this.SendPropertyChanged("export_detail_product_id");
					this.Onexport_detail_product_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_export_amount", DbType="Int")]
		public System.Nullable<int> export_amount
		{
			get
			{
				return this._export_amount;
			}
			set
			{
				if ((this._export_amount != value))
				{
					this.Onexport_amountChanging(value);
					this.SendPropertyChanging();
					this._export_amount = value;
					this.SendPropertyChanged("export_amount");
					this.Onexport_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblexport8_tblexportdetail8", Storage="_tblexport8", ThisKey="export_detail_export_id", OtherKey="export_id", IsForeignKey=true)]
		public tblexport8 tblexport8
		{
			get
			{
				return this._tblexport8.Entity;
			}
			set
			{
				tblexport8 previousValue = this._tblexport8.Entity;
				if (((previousValue != value) 
							|| (this._tblexport8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblexport8.Entity = null;
						previousValue.tblexportdetail8s.Remove(this);
					}
					this._tblexport8.Entity = value;
					if ((value != null))
					{
						value.tblexportdetail8s.Add(this);
						this._export_detail_export_id = value.export_id;
					}
					else
					{
						this._export_detail_export_id = default(string);
					}
					this.SendPropertyChanged("tblexport8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblproduct8_tblexportdetail8", Storage="_tblproduct8", ThisKey="export_detail_product_id", OtherKey="product_id", IsForeignKey=true)]
		public tblproduct8 tblproduct8
		{
			get
			{
				return this._tblproduct8.Entity;
			}
			set
			{
				tblproduct8 previousValue = this._tblproduct8.Entity;
				if (((previousValue != value) 
							|| (this._tblproduct8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblproduct8.Entity = null;
						previousValue.tblexportdetail8s.Remove(this);
					}
					this._tblproduct8.Entity = value;
					if ((value != null))
					{
						value.tblexportdetail8s.Add(this);
						this._export_detail_product_id = value.product_id;
					}
					else
					{
						this._export_detail_product_id = default(string);
					}
					this.SendPropertyChanged("tblproduct8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblimport8")]
	public partial class tblimport8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _import_id;
		
		private System.Nullable<System.DateTime> _import_date;
		
		private string _import_staff_id;
		
		private string _import_distributor_id;
		
		private EntitySet<tblimportdetail8> _tblimportdetail8s;
		
		private EntityRef<tbldistributor8> _tbldistributor8;
		
		private EntityRef<tblstaff8> _tblstaff8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimport_idChanging(string value);
    partial void Onimport_idChanged();
    partial void Onimport_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onimport_dateChanged();
    partial void Onimport_staff_idChanging(string value);
    partial void Onimport_staff_idChanged();
    partial void Onimport_distributor_idChanging(string value);
    partial void Onimport_distributor_idChanged();
    #endregion
		
		public tblimport8()
		{
			this._tblimportdetail8s = new EntitySet<tblimportdetail8>(new Action<tblimportdetail8>(this.attach_tblimportdetail8s), new Action<tblimportdetail8>(this.detach_tblimportdetail8s));
			this._tbldistributor8 = default(EntityRef<tbldistributor8>);
			this._tblstaff8 = default(EntityRef<tblstaff8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string import_id
		{
			get
			{
				return this._import_id;
			}
			set
			{
				if ((this._import_id != value))
				{
					this.Onimport_idChanging(value);
					this.SendPropertyChanging();
					this._import_id = value;
					this.SendPropertyChanged("import_id");
					this.Onimport_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_date", DbType="Date")]
		public System.Nullable<System.DateTime> import_date
		{
			get
			{
				return this._import_date;
			}
			set
			{
				if ((this._import_date != value))
				{
					this.Onimport_dateChanging(value);
					this.SendPropertyChanging();
					this._import_date = value;
					this.SendPropertyChanged("import_date");
					this.Onimport_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_staff_id", DbType="Char(50)")]
		public string import_staff_id
		{
			get
			{
				return this._import_staff_id;
			}
			set
			{
				if ((this._import_staff_id != value))
				{
					if (this._tblstaff8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onimport_staff_idChanging(value);
					this.SendPropertyChanging();
					this._import_staff_id = value;
					this.SendPropertyChanged("import_staff_id");
					this.Onimport_staff_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_distributor_id", DbType="Char(50)")]
		public string import_distributor_id
		{
			get
			{
				return this._import_distributor_id;
			}
			set
			{
				if ((this._import_distributor_id != value))
				{
					if (this._tbldistributor8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onimport_distributor_idChanging(value);
					this.SendPropertyChanging();
					this._import_distributor_id = value;
					this.SendPropertyChanged("import_distributor_id");
					this.Onimport_distributor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblimport8_tblimportdetail8", Storage="_tblimportdetail8s", ThisKey="import_id", OtherKey="import_detail_import_id")]
		public EntitySet<tblimportdetail8> tblimportdetail8s
		{
			get
			{
				return this._tblimportdetail8s;
			}
			set
			{
				this._tblimportdetail8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbldistributor8_tblimport8", Storage="_tbldistributor8", ThisKey="import_distributor_id", OtherKey="distributor_id", IsForeignKey=true)]
		public tbldistributor8 tbldistributor8
		{
			get
			{
				return this._tbldistributor8.Entity;
			}
			set
			{
				tbldistributor8 previousValue = this._tbldistributor8.Entity;
				if (((previousValue != value) 
							|| (this._tbldistributor8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbldistributor8.Entity = null;
						previousValue.tblimport8s.Remove(this);
					}
					this._tbldistributor8.Entity = value;
					if ((value != null))
					{
						value.tblimport8s.Add(this);
						this._import_distributor_id = value.distributor_id;
					}
					else
					{
						this._import_distributor_id = default(string);
					}
					this.SendPropertyChanged("tbldistributor8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblstaff8_tblimport8", Storage="_tblstaff8", ThisKey="import_staff_id", OtherKey="staff_id", IsForeignKey=true)]
		public tblstaff8 tblstaff8
		{
			get
			{
				return this._tblstaff8.Entity;
			}
			set
			{
				tblstaff8 previousValue = this._tblstaff8.Entity;
				if (((previousValue != value) 
							|| (this._tblstaff8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblstaff8.Entity = null;
						previousValue.tblimport8s.Remove(this);
					}
					this._tblstaff8.Entity = value;
					if ((value != null))
					{
						value.tblimport8s.Add(this);
						this._import_staff_id = value.staff_id;
					}
					else
					{
						this._import_staff_id = default(string);
					}
					this.SendPropertyChanged("tblstaff8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblimportdetail8s(tblimportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblimport8 = this;
		}
		
		private void detach_tblimportdetail8s(tblimportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblimport8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblimportdetail8")]
	public partial class tblimportdetail8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _import_detail_import_id;
		
		private string _import_detail_product_id;
		
		private System.Nullable<int> _import_amount;
		
		private EntityRef<tblimport8> _tblimport8;
		
		private EntityRef<tblproduct8> _tblproduct8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onimport_detail_import_idChanging(string value);
    partial void Onimport_detail_import_idChanged();
    partial void Onimport_detail_product_idChanging(string value);
    partial void Onimport_detail_product_idChanged();
    partial void Onimport_amountChanging(System.Nullable<int> value);
    partial void Onimport_amountChanged();
    #endregion
		
		public tblimportdetail8()
		{
			this._tblimport8 = default(EntityRef<tblimport8>);
			this._tblproduct8 = default(EntityRef<tblproduct8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_detail_import_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string import_detail_import_id
		{
			get
			{
				return this._import_detail_import_id;
			}
			set
			{
				if ((this._import_detail_import_id != value))
				{
					if (this._tblimport8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onimport_detail_import_idChanging(value);
					this.SendPropertyChanging();
					this._import_detail_import_id = value;
					this.SendPropertyChanged("import_detail_import_id");
					this.Onimport_detail_import_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_detail_product_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string import_detail_product_id
		{
			get
			{
				return this._import_detail_product_id;
			}
			set
			{
				if ((this._import_detail_product_id != value))
				{
					if (this._tblproduct8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onimport_detail_product_idChanging(value);
					this.SendPropertyChanging();
					this._import_detail_product_id = value;
					this.SendPropertyChanged("import_detail_product_id");
					this.Onimport_detail_product_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_import_amount", DbType="Int")]
		public System.Nullable<int> import_amount
		{
			get
			{
				return this._import_amount;
			}
			set
			{
				if ((this._import_amount != value))
				{
					this.Onimport_amountChanging(value);
					this.SendPropertyChanging();
					this._import_amount = value;
					this.SendPropertyChanged("import_amount");
					this.Onimport_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblimport8_tblimportdetail8", Storage="_tblimport8", ThisKey="import_detail_import_id", OtherKey="import_id", IsForeignKey=true)]
		public tblimport8 tblimport8
		{
			get
			{
				return this._tblimport8.Entity;
			}
			set
			{
				tblimport8 previousValue = this._tblimport8.Entity;
				if (((previousValue != value) 
							|| (this._tblimport8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblimport8.Entity = null;
						previousValue.tblimportdetail8s.Remove(this);
					}
					this._tblimport8.Entity = value;
					if ((value != null))
					{
						value.tblimportdetail8s.Add(this);
						this._import_detail_import_id = value.import_id;
					}
					else
					{
						this._import_detail_import_id = default(string);
					}
					this.SendPropertyChanged("tblimport8");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblproduct8_tblimportdetail8", Storage="_tblproduct8", ThisKey="import_detail_product_id", OtherKey="product_id", IsForeignKey=true)]
		public tblproduct8 tblproduct8
		{
			get
			{
				return this._tblproduct8.Entity;
			}
			set
			{
				tblproduct8 previousValue = this._tblproduct8.Entity;
				if (((previousValue != value) 
							|| (this._tblproduct8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblproduct8.Entity = null;
						previousValue.tblimportdetail8s.Remove(this);
					}
					this._tblproduct8.Entity = value;
					if ((value != null))
					{
						value.tblimportdetail8s.Add(this);
						this._import_detail_product_id = value.product_id;
					}
					else
					{
						this._import_detail_product_id = default(string);
					}
					this.SendPropertyChanged("tblproduct8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblproduct8")]
	public partial class tblproduct8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private string _product_name;
		
		private string _product_brand;
		
		private string _product_image;
		
		private string _product_specification;
		
		private string _product_feature;
		
		private System.Nullable<double> _product_exprice;
		
		private System.Nullable<double> _product_imprice;
		
		private System.Nullable<int> _product_amount;
		
		private string _product_type_id;
		
		private EntitySet<tblexportdetail8> _tblexportdetail8s;
		
		private EntitySet<tblimportdetail8> _tblimportdetail8s;
		
		private EntityRef<tbltype8> _tbltype8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_brandChanging(string value);
    partial void Onproduct_brandChanged();
    partial void Onproduct_imageChanging(string value);
    partial void Onproduct_imageChanged();
    partial void Onproduct_specificationChanging(string value);
    partial void Onproduct_specificationChanged();
    partial void Onproduct_featureChanging(string value);
    partial void Onproduct_featureChanged();
    partial void Onproduct_expriceChanging(System.Nullable<double> value);
    partial void Onproduct_expriceChanged();
    partial void Onproduct_impriceChanging(System.Nullable<double> value);
    partial void Onproduct_impriceChanged();
    partial void Onproduct_amountChanging(System.Nullable<int> value);
    partial void Onproduct_amountChanged();
    partial void Onproduct_type_idChanging(string value);
    partial void Onproduct_type_idChanged();
    #endregion
		
		public tblproduct8()
		{
			this._tblexportdetail8s = new EntitySet<tblexportdetail8>(new Action<tblexportdetail8>(this.attach_tblexportdetail8s), new Action<tblexportdetail8>(this.detach_tblexportdetail8s));
			this._tblimportdetail8s = new EntitySet<tblimportdetail8>(new Action<tblimportdetail8>(this.attach_tblimportdetail8s), new Action<tblimportdetail8>(this.detach_tblimportdetail8s));
			this._tbltype8 = default(EntityRef<tbltype8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(MAX)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_brand", DbType="NVarChar(MAX)")]
		public string product_brand
		{
			get
			{
				return this._product_brand;
			}
			set
			{
				if ((this._product_brand != value))
				{
					this.Onproduct_brandChanging(value);
					this.SendPropertyChanging();
					this._product_brand = value;
					this.SendPropertyChanged("product_brand");
					this.Onproduct_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_image", DbType="NVarChar(100)")]
		public string product_image
		{
			get
			{
				return this._product_image;
			}
			set
			{
				if ((this._product_image != value))
				{
					this.Onproduct_imageChanging(value);
					this.SendPropertyChanging();
					this._product_image = value;
					this.SendPropertyChanged("product_image");
					this.Onproduct_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_specification", DbType="NVarChar(MAX)")]
		public string product_specification
		{
			get
			{
				return this._product_specification;
			}
			set
			{
				if ((this._product_specification != value))
				{
					this.Onproduct_specificationChanging(value);
					this.SendPropertyChanging();
					this._product_specification = value;
					this.SendPropertyChanged("product_specification");
					this.Onproduct_specificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_feature", DbType="NVarChar(MAX)")]
		public string product_feature
		{
			get
			{
				return this._product_feature;
			}
			set
			{
				if ((this._product_feature != value))
				{
					this.Onproduct_featureChanging(value);
					this.SendPropertyChanging();
					this._product_feature = value;
					this.SendPropertyChanged("product_feature");
					this.Onproduct_featureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_exprice", DbType="Float")]
		public System.Nullable<double> product_exprice
		{
			get
			{
				return this._product_exprice;
			}
			set
			{
				if ((this._product_exprice != value))
				{
					this.Onproduct_expriceChanging(value);
					this.SendPropertyChanging();
					this._product_exprice = value;
					this.SendPropertyChanged("product_exprice");
					this.Onproduct_expriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_imprice", DbType="Float")]
		public System.Nullable<double> product_imprice
		{
			get
			{
				return this._product_imprice;
			}
			set
			{
				if ((this._product_imprice != value))
				{
					this.Onproduct_impriceChanging(value);
					this.SendPropertyChanging();
					this._product_imprice = value;
					this.SendPropertyChanged("product_imprice");
					this.Onproduct_impriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_amount", DbType="Int")]
		public System.Nullable<int> product_amount
		{
			get
			{
				return this._product_amount;
			}
			set
			{
				if ((this._product_amount != value))
				{
					this.Onproduct_amountChanging(value);
					this.SendPropertyChanging();
					this._product_amount = value;
					this.SendPropertyChanged("product_amount");
					this.Onproduct_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_type_id", DbType="Char(50)")]
		public string product_type_id
		{
			get
			{
				return this._product_type_id;
			}
			set
			{
				if ((this._product_type_id != value))
				{
					if (this._tbltype8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_type_idChanging(value);
					this.SendPropertyChanging();
					this._product_type_id = value;
					this.SendPropertyChanged("product_type_id");
					this.Onproduct_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblproduct8_tblexportdetail8", Storage="_tblexportdetail8s", ThisKey="product_id", OtherKey="export_detail_product_id")]
		public EntitySet<tblexportdetail8> tblexportdetail8s
		{
			get
			{
				return this._tblexportdetail8s;
			}
			set
			{
				this._tblexportdetail8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblproduct8_tblimportdetail8", Storage="_tblimportdetail8s", ThisKey="product_id", OtherKey="import_detail_product_id")]
		public EntitySet<tblimportdetail8> tblimportdetail8s
		{
			get
			{
				return this._tblimportdetail8s;
			}
			set
			{
				this._tblimportdetail8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbltype8_tblproduct8", Storage="_tbltype8", ThisKey="product_type_id", OtherKey="type_id", IsForeignKey=true)]
		public tbltype8 tbltype8
		{
			get
			{
				return this._tbltype8.Entity;
			}
			set
			{
				tbltype8 previousValue = this._tbltype8.Entity;
				if (((previousValue != value) 
							|| (this._tbltype8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbltype8.Entity = null;
						previousValue.tblproduct8s.Remove(this);
					}
					this._tbltype8.Entity = value;
					if ((value != null))
					{
						value.tblproduct8s.Add(this);
						this._product_type_id = value.type_id;
					}
					else
					{
						this._product_type_id = default(string);
					}
					this.SendPropertyChanged("tbltype8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblexportdetail8s(tblexportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblproduct8 = this;
		}
		
		private void detach_tblexportdetail8s(tblexportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblproduct8 = null;
		}
		
		private void attach_tblimportdetail8s(tblimportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblproduct8 = this;
		}
		
		private void detach_tblimportdetail8s(tblimportdetail8 entity)
		{
			this.SendPropertyChanging();
			entity.tblproduct8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblstaff8")]
	public partial class tblstaff8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _staff_id;
		
		private string _staff_name;
		
		private System.Nullable<System.DateTime> _staff_birth;
		
		private string _staff_gender;
		
		private string _staff_id_number;
		
		private string _staff_address;
		
		private string _staff_phone;
		
		private string _staff_degree_id;
		
		private EntitySet<tblexport8> _tblexport8s;
		
		private EntitySet<tblimport8> _tblimport8s;
		
		private EntityRef<tbldegree8> _tbldegree8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstaff_idChanging(string value);
    partial void Onstaff_idChanged();
    partial void Onstaff_nameChanging(string value);
    partial void Onstaff_nameChanged();
    partial void Onstaff_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onstaff_birthChanged();
    partial void Onstaff_genderChanging(string value);
    partial void Onstaff_genderChanged();
    partial void Onstaff_id_numberChanging(string value);
    partial void Onstaff_id_numberChanged();
    partial void Onstaff_addressChanging(string value);
    partial void Onstaff_addressChanged();
    partial void Onstaff_phoneChanging(string value);
    partial void Onstaff_phoneChanged();
    partial void Onstaff_degree_idChanging(string value);
    partial void Onstaff_degree_idChanged();
    #endregion
		
		public tblstaff8()
		{
			this._tblexport8s = new EntitySet<tblexport8>(new Action<tblexport8>(this.attach_tblexport8s), new Action<tblexport8>(this.detach_tblexport8s));
			this._tblimport8s = new EntitySet<tblimport8>(new Action<tblimport8>(this.attach_tblimport8s), new Action<tblimport8>(this.detach_tblimport8s));
			this._tbldegree8 = default(EntityRef<tbldegree8>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string staff_id
		{
			get
			{
				return this._staff_id;
			}
			set
			{
				if ((this._staff_id != value))
				{
					this.Onstaff_idChanging(value);
					this.SendPropertyChanging();
					this._staff_id = value;
					this.SendPropertyChanged("staff_id");
					this.Onstaff_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="NVarChar(50)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this.Onstaff_nameChanging(value);
					this.SendPropertyChanging();
					this._staff_name = value;
					this.SendPropertyChanged("staff_name");
					this.Onstaff_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_birth", DbType="Date")]
		public System.Nullable<System.DateTime> staff_birth
		{
			get
			{
				return this._staff_birth;
			}
			set
			{
				if ((this._staff_birth != value))
				{
					this.Onstaff_birthChanging(value);
					this.SendPropertyChanging();
					this._staff_birth = value;
					this.SendPropertyChanged("staff_birth");
					this.Onstaff_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_gender", DbType="NChar(10)")]
		public string staff_gender
		{
			get
			{
				return this._staff_gender;
			}
			set
			{
				if ((this._staff_gender != value))
				{
					this.Onstaff_genderChanging(value);
					this.SendPropertyChanging();
					this._staff_gender = value;
					this.SendPropertyChanged("staff_gender");
					this.Onstaff_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_id_number", DbType="VarChar(50)")]
		public string staff_id_number
		{
			get
			{
				return this._staff_id_number;
			}
			set
			{
				if ((this._staff_id_number != value))
				{
					this.Onstaff_id_numberChanging(value);
					this.SendPropertyChanging();
					this._staff_id_number = value;
					this.SendPropertyChanged("staff_id_number");
					this.Onstaff_id_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_address", DbType="NVarChar(MAX)")]
		public string staff_address
		{
			get
			{
				return this._staff_address;
			}
			set
			{
				if ((this._staff_address != value))
				{
					this.Onstaff_addressChanging(value);
					this.SendPropertyChanging();
					this._staff_address = value;
					this.SendPropertyChanged("staff_address");
					this.Onstaff_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_phone", DbType="VarChar(50)")]
		public string staff_phone
		{
			get
			{
				return this._staff_phone;
			}
			set
			{
				if ((this._staff_phone != value))
				{
					this.Onstaff_phoneChanging(value);
					this.SendPropertyChanging();
					this._staff_phone = value;
					this.SendPropertyChanged("staff_phone");
					this.Onstaff_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_degree_id", DbType="Char(50)")]
		public string staff_degree_id
		{
			get
			{
				return this._staff_degree_id;
			}
			set
			{
				if ((this._staff_degree_id != value))
				{
					if (this._tbldegree8.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onstaff_degree_idChanging(value);
					this.SendPropertyChanging();
					this._staff_degree_id = value;
					this.SendPropertyChanged("staff_degree_id");
					this.Onstaff_degree_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblstaff8_tblexport8", Storage="_tblexport8s", ThisKey="staff_id", OtherKey="export_staff_id")]
		public EntitySet<tblexport8> tblexport8s
		{
			get
			{
				return this._tblexport8s;
			}
			set
			{
				this._tblexport8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblstaff8_tblimport8", Storage="_tblimport8s", ThisKey="staff_id", OtherKey="import_staff_id")]
		public EntitySet<tblimport8> tblimport8s
		{
			get
			{
				return this._tblimport8s;
			}
			set
			{
				this._tblimport8s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbldegree8_tblstaff8", Storage="_tbldegree8", ThisKey="staff_degree_id", OtherKey="degree_id", IsForeignKey=true)]
		public tbldegree8 tbldegree8
		{
			get
			{
				return this._tbldegree8.Entity;
			}
			set
			{
				tbldegree8 previousValue = this._tbldegree8.Entity;
				if (((previousValue != value) 
							|| (this._tbldegree8.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbldegree8.Entity = null;
						previousValue.tblstaff8s.Remove(this);
					}
					this._tbldegree8.Entity = value;
					if ((value != null))
					{
						value.tblstaff8s.Add(this);
						this._staff_degree_id = value.degree_id;
					}
					else
					{
						this._staff_degree_id = default(string);
					}
					this.SendPropertyChanged("tbldegree8");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblexport8s(tblexport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblstaff8 = this;
		}
		
		private void detach_tblexport8s(tblexport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblstaff8 = null;
		}
		
		private void attach_tblimport8s(tblimport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblstaff8 = this;
		}
		
		private void detach_tblimport8s(tblimport8 entity)
		{
			this.SendPropertyChanging();
			entity.tblstaff8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbltype8")]
	public partial class tbltype8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _type_id;
		
		private string _type_name;
		
		private EntitySet<tblproduct8> _tblproduct8s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontype_idChanging(string value);
    partial void Ontype_idChanged();
    partial void Ontype_nameChanging(string value);
    partial void Ontype_nameChanged();
    #endregion
		
		public tbltype8()
		{
			this._tblproduct8s = new EntitySet<tblproduct8>(new Action<tblproduct8>(this.attach_tblproduct8s), new Action<tblproduct8>(this.detach_tblproduct8s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string type_id
		{
			get
			{
				return this._type_id;
			}
			set
			{
				if ((this._type_id != value))
				{
					this.Ontype_idChanging(value);
					this.SendPropertyChanging();
					this._type_id = value;
					this.SendPropertyChanged("type_id");
					this.Ontype_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_name", DbType="NVarChar(MAX)")]
		public string type_name
		{
			get
			{
				return this._type_name;
			}
			set
			{
				if ((this._type_name != value))
				{
					this.Ontype_nameChanging(value);
					this.SendPropertyChanging();
					this._type_name = value;
					this.SendPropertyChanged("type_name");
					this.Ontype_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbltype8_tblproduct8", Storage="_tblproduct8s", ThisKey="type_id", OtherKey="product_type_id")]
		public EntitySet<tblproduct8> tblproduct8s
		{
			get
			{
				return this._tblproduct8s;
			}
			set
			{
				this._tblproduct8s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblproduct8s(tblproduct8 entity)
		{
			this.SendPropertyChanging();
			entity.tbltype8 = this;
		}
		
		private void detach_tblproduct8s(tblproduct8 entity)
		{
			this.SendPropertyChanging();
			entity.tbltype8 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbluser8")]
	public partial class tbluser8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _user_pass;
		
		private string _user_permission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    partial void Onuser_permissionChanging(string value);
    partial void Onuser_permissionChanged();
    #endregion
		
		public tbluser8()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_permission", DbType="NChar(10)")]
		public string user_permission
		{
			get
			{
				return this._user_permission;
			}
			set
			{
				if ((this._user_permission != value))
				{
					this.Onuser_permissionChanging(value);
					this.SendPropertyChanging();
					this._user_permission = value;
					this.SendPropertyChanged("user_permission");
					this.Onuser_permissionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
