#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="namngu")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttblproduct8(tblproduct8 instance);
    partial void Updatetblproduct8(tblproduct8 instance);
    partial void Deletetblproduct8(tblproduct8 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleApp1.Properties.Settings.Default.namnguConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblproduct8> tblproduct8s
		{
			get
			{
				return this.GetTable<tblproduct8>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblproduct8")]
	public partial class tblproduct8 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private string _product_name;
		
		private string _product_brand;
		
		private string _product_image;
		
		private string _product_specification;
		
		private string _product_feature;
		
		private System.Nullable<double> _product_exprice;
		
		private System.Nullable<double> _product_imprice;
		
		private System.Nullable<int> _product_amount;
		
		private string _product_type_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_brandChanging(string value);
    partial void Onproduct_brandChanged();
    partial void Onproduct_imageChanging(string value);
    partial void Onproduct_imageChanged();
    partial void Onproduct_specificationChanging(string value);
    partial void Onproduct_specificationChanged();
    partial void Onproduct_featureChanging(string value);
    partial void Onproduct_featureChanged();
    partial void Onproduct_expriceChanging(System.Nullable<double> value);
    partial void Onproduct_expriceChanged();
    partial void Onproduct_impriceChanging(System.Nullable<double> value);
    partial void Onproduct_impriceChanged();
    partial void Onproduct_amountChanging(System.Nullable<int> value);
    partial void Onproduct_amountChanged();
    partial void Onproduct_type_idChanging(string value);
    partial void Onproduct_type_idChanged();
    #endregion
		
		public tblproduct8()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(MAX)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_brand", DbType="NVarChar(MAX)")]
		public string product_brand
		{
			get
			{
				return this._product_brand;
			}
			set
			{
				if ((this._product_brand != value))
				{
					this.Onproduct_brandChanging(value);
					this.SendPropertyChanging();
					this._product_brand = value;
					this.SendPropertyChanged("product_brand");
					this.Onproduct_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_image", DbType="NVarChar(100)")]
		public string product_image
		{
			get
			{
				return this._product_image;
			}
			set
			{
				if ((this._product_image != value))
				{
					this.Onproduct_imageChanging(value);
					this.SendPropertyChanging();
					this._product_image = value;
					this.SendPropertyChanged("product_image");
					this.Onproduct_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_specification", DbType="NVarChar(MAX)")]
		public string product_specification
		{
			get
			{
				return this._product_specification;
			}
			set
			{
				if ((this._product_specification != value))
				{
					this.Onproduct_specificationChanging(value);
					this.SendPropertyChanging();
					this._product_specification = value;
					this.SendPropertyChanged("product_specification");
					this.Onproduct_specificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_feature", DbType="NVarChar(MAX)")]
		public string product_feature
		{
			get
			{
				return this._product_feature;
			}
			set
			{
				if ((this._product_feature != value))
				{
					this.Onproduct_featureChanging(value);
					this.SendPropertyChanging();
					this._product_feature = value;
					this.SendPropertyChanged("product_feature");
					this.Onproduct_featureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_exprice", DbType="Float")]
		public System.Nullable<double> product_exprice
		{
			get
			{
				return this._product_exprice;
			}
			set
			{
				if ((this._product_exprice != value))
				{
					this.Onproduct_expriceChanging(value);
					this.SendPropertyChanging();
					this._product_exprice = value;
					this.SendPropertyChanged("product_exprice");
					this.Onproduct_expriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_imprice", DbType="Float")]
		public System.Nullable<double> product_imprice
		{
			get
			{
				return this._product_imprice;
			}
			set
			{
				if ((this._product_imprice != value))
				{
					this.Onproduct_impriceChanging(value);
					this.SendPropertyChanging();
					this._product_imprice = value;
					this.SendPropertyChanged("product_imprice");
					this.Onproduct_impriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_amount", DbType="Int")]
		public System.Nullable<int> product_amount
		{
			get
			{
				return this._product_amount;
			}
			set
			{
				if ((this._product_amount != value))
				{
					this.Onproduct_amountChanging(value);
					this.SendPropertyChanging();
					this._product_amount = value;
					this.SendPropertyChanged("product_amount");
					this.Onproduct_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_type_id", DbType="Char(50)")]
		public string product_type_id
		{
			get
			{
				return this._product_type_id;
			}
			set
			{
				if ((this._product_type_id != value))
				{
					this.Onproduct_type_idChanging(value);
					this.SendPropertyChanging();
					this._product_type_id = value;
					this.SendPropertyChanged("product_type_id");
					this.Onproduct_type_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
